name: Deploy Laravel to Rumahweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /home/elih9626/repositories/perpustakaan

            git fetch origin
            git reset --hard origin/main

            composer install --no-dev --optimize-autoloader

            php artisan optimize:clear

            php artisan config:cache

            php artisan route:cache

            php artisan view:cache