name: Deploy Laravel to Rumahweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /home/elih9626/repositories/perpustakaan

            git pull origin main

            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            cp -R public/* /home/elih9626/public_html/