name: Test Secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Host Length
        run: |
          echo "Length=${#HOST}"
        env:
          HOST: ${{ secrets.HOST }}